using System;
using System.Collections.Generic;
using System.Text;

namespace RemitaIntegrate.NET
{
    public class RemitaPost
    {
        public string MerchantId { get; set; }
        public string Hash { get; set; }
        public string Rrr { get; set; }
        public string ResponseUrl { get; set; }

        public PaymentType RemitaPaymentType { get; set; }
        public string OrderId { get; set; } //generated by the merchant and sent to remita
        public string PayerId { get; set; }
        public string PayerEmail { get; set; }
        public string PayerName { get; set; }
        public string Amount { get; set; }
        public string PayerPhone { get; set; }
        public string ServiceTypeId { get; set; }
    }
}
